global:
  smtp_smarthost: 'smtp.163.com:465'
  smtp_from: 'yann@163.com'
  smtp_auth_username: 'yann@163.com'
  smtp_auth_password: 'your-password'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: email

receivers:
- name: 'email'
  email_configs:
  - to: 'yann@163.com'
inhibit_rules:
 - source_match:
     severity: 'critical'
   target_match:
     severity: 'warning'
   equal: ['alertname', 'dev', 'instance']
