global:
  scrape_interval:     20s
  evaluation_interval: 15s

# Alertmanager 
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

# 触发器
rule_files:
  - "alert.yml"

# 搜刮配置
scrape_configs:
  - job_name: 'prometheus'
    # 覆盖
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']
      
  - job_name: 'alertmanager'
    scrape_interval: 15s
    static_configs:
    - targets: ['alertmanager:9093']
